# Numpy

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

In [ ]:
import numpy as np

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [ ]:
everything = np.loadtxt('minutes_n_ingredients.csv', skiprows=1, delimiter=',', dtype=np.int32)
print(everything[:5, :])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [ ]:
rec_mean = np.mean(everything[:, 1:], axis=0)
print(rec_mean)

[2.16010017e+04 9.05528000e+00]


In [ ]:
rec_min = np.amin(everything[:, 1:], axis=0)
print(rec_min)

[0 1]


In [ ]:
rec_max = np.amax(everything[:, 1:], axis=0)
print(rec_max)

[2147483647         39]


In [ ]:
rec_median = np.median(everything[:, 1:], axis=0)
print(rec_median)

[40.  9.]


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [ ]:
q = np.quantile(everything[:, 1], 0.75)
print(q)

65.0


In [ ]:
everything[:,1] = np.clip(everything[:, 1], None, q)

In [ ]:
print(everything)

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 ...
 [498432     65     15]
 [370915      5      4]
 [ 81993     65     14]]


4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [ ]:
equal_zero = np.count_nonzero(everything[:,1]==0)
print(equal_zero)

479


In [ ]:
everything[:,1][everything[:,1] == 0] = 1
print(everything) 
print(np.count_nonzero(everything[:,1]==0))

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 ...
 [498432     65     15]
 [370915      5      4]
 [ 81993     65     14]]
0


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [ ]:
num_unique = len(np.unique(everything[:,1:], axis=0))
print(num_unique)

1135


6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [ ]:
n_ingridiens, n_n = np.unique(everything[:,2], return_counts=True)
unique_ingridients = np.full((len(n_ingridiens), 2), 0, dtype=np.int32)
unique_ingridients[:,0] = n_ingridiens
unique_ingridients[:,1] = n_n
print(unique_ingridients)

[[    1    13]
 [    2   926]
 [    3  2895]
 [    4  5515]
 [    5  7913]
 [    6  9376]
 [    7 10628]
 [    8 10951]
 [    9 10585]
 [   10  9591]
 [   11  8297]
 [   12  6605]
 [   13  4997]
 [   14  3663]
 [   15  2595]
 [   16  1767]
 [   17  1246]
 [   18   790]
 [   19   573]
 [   20   376]
 [   21   217]
 [   22   161]
 [   23   105]
 [   24    69]
 [   25    50]
 [   26    28]
 [   27    16]
 [   28    16]
 [   29    12]
 [   30    12]
 [   31     3]
 [   32     1]
 [   33     2]
 [   34     1]
 [   35     3]
 [   37     1]
 [   39     1]]


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [ ]:
new = everything
res = new[new[:,2] <= 5]
print(res.shape)
print(res)

(17262, 3)
[[446597     15      5]
 [204134      5      3]
 [ 25623      6      4]
 ...
 [ 52088     60      5]
 [128811     15      4]
 [370915      5      4]]


8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [ ]:
a = everything[:, 1]
b = everything[:, 2]
c = np.divide(b, a)
print(c)

[0.26666667 0.28       0.6        ... 0.23076923 0.8        0.21538462]


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [ ]:
minutes_sorted = everything[everything[:, 1].argsort()]
top_100 = minutes_sorted[-100:, :]
np.mean(top_100[:, 2])

9.96

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [ ]:
ids = np.random.choice(everything[:,0], size=10, replace=False)
mask = np.isin(everything[:,0], ids)
print(everything[mask])

[[ 59155     65     10]
 [382629     25      6]
 [ 65947     65     13]
 [107863     40     12]
 [107545     65     12]
 [191198     30     12]
 [282319      5      6]
 [226503     38     14]
 [499511     35     19]
 [172498     65      9]]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [ ]:
less_mean = np.count_nonzero(everything[:,2] < rec_mean[1])
percent_less_mean = less_mean / len(everything[:,2]) * 100
print(percent_less_mean)

58.802


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [ ]:
show_easy = np.full((len(everything[:,1]), 4), 0, dtype=np.int32)
show_easy[:, :3] = everything;
show_easy[:, 3] = np.where((show_easy[:, 1]<20) & (show_easy[:, 2] <= 5), 1, 0)
print(show_easy)
easy_number = np.count_nonzero(show_easy[:,3]==1)
print(easy_number)

[[127244     60     16      0]
 [ 23891     25      7      0]
 [ 94746     10      6      0]
 ...
 [498432     65     15      0]
 [370915      5      4      1]
 [ 81993     65     14      0]]
8315


13. Выведите процент "простых" рецептов в датасете

In [ ]:
percent_easy = easy_number / len(everything[:,2]) * 100
print(percent_easy)

8.315


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.